# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Before running goreleaser create a tag and push it:
#  - git tag -a v0.2.0 -m "Adding Docker to the publish"
#  - git push origin v0.2.0

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
    # go test all
    # - go test -cover -race ./...
builds:
  -
    main: ./app/cmd/goaws.go
    binary: goaws
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    use: buildx
    image_templates:
      - "admiralpiett/goaws:{{ .Tag }}-amd64"
    extra_files:
      - app/conf/goaws.yaml
    build_flag_templates:
      - "--platform=linux/amd64"
  - goos: linux
    goarch: arm64
    dockerfile: goreleaser.dockerfile
    use: buildx
    image_templates:
      - "admiralpiett/goaws:{{ .Tag }}-arm64"
    extra_files:
      - app/conf/goaws.yaml
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
- name_template: admiralpiett/goaws:{{ .Tag }}
  image_templates:
  - admiralpiett/goaws:{{ .Tag }}-amd64
  - admiralpiett/goaws:{{ .Tag }}-arm64
- name_template: admiralpiett/goaws:latest
  image_templates:
  - admiralpiett/goaws:{{ .Tag }}-amd64
  - admiralpiett/goaws:{{ .Tag }}-arm64

archives:
  - id: archive_names
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

